  version: '3'
  services:
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_DB=cognitus
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5433:5432"
      restart: always

    web:
      image: web
      build: .
      container_name: web
      command: "python cognitus_django/manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
    
    algorithm:
        image: algorithm
        build: .
        command: "python cognitus_flask/run.py"
        container_name: algorithm
        volumes:
        - .:/code
        ports:
            - '5000:5000'
        links:
            - redis
            - algorithm_celery

    algorithm_celery:
        image: algorithm_celery
        build: .
        command: "celery -A cognitus_flask.services.train.celery worker --loglevel=info"
        container_name: algorithm_celery
        volumes:
        - .:/code
        user: nobody
        links:
            - redis

    redis:
        image: redis
        container_name: redis
        command: redis-server
        ports:
            - '6379:6379'