  version: '3'
  services:
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_DB=cognitus
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5433:5432"
      restart: always
    web:
      build: .
      container_name: web
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
    

