version: '3'
services:
    algorithm:
        build: .
        command: "python run.py"
        container_name: algorithm
        ports:
            - '5000:5000'
        links:
            - redis
            - algorithm_celery
        volumes:
            - .:/usr/src/app:ro

    algorithm_celery:
        build: .
        command: "celery -A services.train.celery worker --loglevel=info"
        container_name: algorithm_celery
        user: nobody
        links:
            - redis
        volumes:
            - .:/usr/src/app:ro

    redis:
        image: redis
        container_name: redis
        command: redis-server
        ports:
            - '6379:6379'